### ISSUE TITLE
Default import isn't CSV

### ISSUE THREAD

**Issue by jamessewell** [timescale/timescaledb-parallel-copy#10]
Hi,

At the moment you do your default import with `--delimiter ,`, but this is still really TSV mode, not CSV.

I got problems with this when I was using a composite type, ie:

```
   composite_id   |          time          | type |             detail
------------------+------------------------+------+--------------------------------
 (4,158222831445) | 2018-08-21 12:26:11+10 |   10 | {"x": 69.28222, "y": 116.6612}
```

This produces a CSV of:
```
"(4,158222831445)",2018-08-21 12:26:11+10,10,"{""x"": 69.28222, ""y"": 116.6612}"
```

Which doesn't load with the loader unless you use  `-copy-options CSV` to force CSV. which fixes the problem by respecting CSV quoting.

This should probably be the default, or at least mentioned in the readme

**Comment by RobAtticus** [comment]
I think I agree it should be the default, so I will update that.
