### ISSUE TITLE
High Vulnerability in golang.org/x/crypto

### ISSUE THREAD

**Issue by adk-stealthpath** [timescale/timescaledb-parallel-copy#103]
Hello, 

We are working on deploying TimescaleDB via the Bitnami Postgres helm chart and part of our procedures is to perform a security scan on all built images. Unfortunately it's coming up with the following vulnerability in this package which I found following the dockerfile in the [timescale dockerfile repo](https://github.com/timescale/timescaledb-docker/blob/main/bitnami/Dockerfile)

```
NAME                 INSTALLED  FIXED-IN  TYPE       VULNERABILITY        SEVERITY 
golang.org/x/crypto  v0.27.0    0.31.0    go-module  GHSA-v778-237x-gjrc  High    
```

I'm more than happy to provide a PR to update the package, but I wanted to check here in case you had your own procedure for these things. 

Thanks for your help!

**Comment by MetalBlueberry** [comment]
it has been updated here https://github.com/timescale/timescaledb-parallel-copy/pull/104

**Comment by adk-stealthpath** [comment]
Thank you! It's much appreciated!
