### ISSUE TITLE
Multiline records

### ISSUE THREAD

**Issue by kanazir** [timescale/timescaledb-parallel-copy#19]
The app will fail if you have multiline records in the CSV file.
For example, I have a lot of records like this:

```
581455383,666,,1,11,111111111110,String,"REALIZACIJE DO 12h:
KUKURUZ VESTACKI SUV ROD 2015,
100t, cena 16.1;
SOJA ZRNO MERKANTILNA ROD 2015,
200t, cena 41;
CENE SU BEZ PDV-a",2,2015-10-30 13:40:09.811055,2015-10-30 13:40:06,2015-10-30 13:40:11.651163,2015-10-30 13:40:16.427218,51781933,,85450933,1.10,0000033dba1f0@150b8c3328c,DeliveredToTerminal,,,1
```

Your app reads CSV file line by line and it is unable to detect multiline records.

**Comment by binakot** [comment]
Looks like I ran into a similar problem 😿 

And recommended method for migration to Timescale is not available for me: 
https://docs.timescale.com/latest/getting-started/migrating-data#csv-import

**Comment by jchampio** [comment]
This should now be fixed as of the above commit. If you have the ability to test that out and confirm, that'd be fantastic! (The fix is not yet in a released version, so you'd need to install `@HEAD` to test the prerelease.) Please reopen if you find any issues.
