### ISSUE TITLE
Default --token-size value triggers a warning

### ISSUE THREAD

**Issue by ctberthiaume** [timescale/timescaledb-parallel-copy#28]
Running the command with the default value for the new `--token-size` option triggers a warning, which may not be intended.

```
WARNING: provided --token-size (65536) is smaller than default (65536), ignoring
```

The check here could be changed from `<=` to `<` to prevent the warning when not specifying a token size.

https://github.com/timescale/timescaledb-parallel-copy/blob/3655b5ea7f3b8f0a8d42236db9031b442db60546/cmd/timescaledb-parallel-copy/main.go#L128

**Comment by RobAtticus** [comment]
Doh, thought I tested that case, thanks

**Comment by RobAtticus** [comment]
Should be working on the latest!
