### ISSUE TITLE
-split parameter does not accept tabs

### ISSUE THREAD

**Issue by kmatt** [timescale/timescaledb-parallel-copy#3]
**$ ./timescaledb-parallel-copy -db-name testdb -table customer_test -file customer_20170701.dat -split "\t**"

```
panic: pq: COPY delimiter must be a single one-byte character

goroutine 5 [running]:
panic(0x5e16a0, 0xc4203ac000)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.processBatches(0xc420010a30, 0xc420072120)
        /home/matt/source/timescaledb-parallel-copy/main.go:188 +0x712
created by main.main
        /home/matt/source/timescaledb-parallel-copy/main.go:101 +0x191
```

**Comment by kmatt** [comment]
I'm trying an approach where tab delimited data is its own parameter, because that error seems to be coming from libpq, and the default copy implementation defaults to tab delimited data.

**Comment by RobAtticus** [comment]
Should be fixed as of
https://github.com/timescale/timescaledb-parallel-copy/commit/940ead8da31690323cca124a27389850f3fe72ff

Please let me know if that doesn't work

**Comment by kmatt** [comment]
Works for me!
