### ISSUE TITLE
bash: timescaledb-parallel-copy: command not found

### ISSUE THREAD

**Issue by minh5** [timescale/timescaledb-parallel-copy#4]
I'm trying to run this parallel copy because loading in using `COPY` crashes my server. However when I run it, I get this error `-bash: timescaledb-parallel-copy: command not found`

I have confirmed that I have Go

```
Minhs-MBP:~ minhmai$ go version
go version go1.9.2 darwin/amd64
``` 

I have also tried to install the program multiple times using `go get github.com/timescale/timescaledb-parallel-copy` but every time I run it, I get the same error.

I'm not familiar with Go, just an fyi. Am I missing something?

**Comment by RobAtticus** [comment]
You'll need to add `$GOPATH/bin` to your `PATH` variable. So each bash session you'll need to do `export PATH=$PATH:$GOPATH/bin` or you can put it in your `~/.bashrc` file to have it load each time.

**Comment by minh5** [comment]
Thanks that works!

**Comment by BilalS10** [comment]
I am facing the same issue and even after adding the go path it doesnt work
