### ISSUE TITLE
Timestamp column format in CSV

### ISSUE THREAD

**Issue by The-Riddles** [timescale/timescaledb-parallel-copy#5]
Hi:

What is the format of the time column in CSV (for timestamp type)?

I'm trying to use
`201711211230/20171121 1230/2017-11-21 12:30:00/2017-11-21 12:30:00.000`
and more which timestamp format I want to filing time column, but i also get error below:

```
panic: pq: invalid input syntax for type timestamp: "MINUTE_5_ID"

goroutine 20 [running]:
main.processBatches(0xc4200a8260, 0xc4200b6060)
        /opt/program/timescaledb-parallel-copy-master/main.go:225 +0xb3d
created by main.main
        /opt/program/timescaledb-parallel-copy-master/main.go:105 +0x178
```

**Comment by RobAtticus** [comment]
Hi @The-Riddles , sorry for the delay.

It looks like you have something called "MINUTE_5_ID" in the spot it is expecting a timestamp which is causing the error. If your CSV had a header line, you'll want to get rid of that.

I believe the last two formats your suggested should work for timestamps.

**Comment by The-Riddles** [comment]
Hi @RobAtticus , that's nothing. 

It works when I deleted CSV header line. I test my data input shell and get output below, It fits my expectations.
```
COPY 632850, took 8.193225129s with 4 worker(s) (mean rate 77240.645782/sec)
```

And I Used Timestamp format ```yyyy-MM-dd hh24:mi:ss```

thanks for reply.

**Comment by RobAtticus** [comment]
Sorry, I don't remember where we left this. Did you get it working or is there still a problem?

**Comment by The-Riddles** [comment]
Hey @RobAtticus , Now it's running normally，and I've used it in the production environment.

Thanks again.

**Comment by RobAtticus** [comment]
Great! Don't hesitate to reach out or join our slack if you haven't ( http://slack-login.timescale.com/ ), always happy to help and hear more about how you're using us.
