### ISSUE TITLE
[Bug]: missing values on large inserts

### ISSUE THREAD

**Issue by hjfeldy** [timescale/timescaledb-parallel-copy#59]
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Data ingestion

### What happened?

Upon inserting a large CSV of cryptocurrency data, certain rows are missing. 
[timescaleIssue.zip](https://github.com/timescale/timescaledb/files/8613007/timescaleIssue.zip)

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

12

### What operating system did you use?

Ubuntu 20.04 LTS x86_64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
psql:testDB.sql:1: NOTICE:  extension "timescaledb" already exists, skipping
     create_hypertable
 -------------------------
  (8,public,test_table,t)
 (1 row)

                add_dimension
 --------------------------------------------
  (30,public,test_table,collection_window,t)
 (1 row)

             add_dimension
 --------------------------------------
  (31,public,test_table,roll_window,t)
 (1 row)

          add_dimension
 -------------------------------
  (32,public,test_table,pair,t)
 (1 row)

 Performing vanilla postgres COPY command...
 COPY 3748508
 Results:
  count
 -------
      1
 (1 row)

 Resetting DB
 psql:testDB.sql:1: NOTICE:  extension "timescaledb" already exists, skipping
     create_hypertable
 -------------------------
  (9,public,test_table,t)
 (1 row)

                add_dimension
 --------------------------------------------
  (34,public,test_table,collection_window,t)
 (1 row)

             add_dimension
 --------------------------------------
  (35,public,test_table,roll_window,t)
 (1 row)

          add_dimension
 -------------------------------
  (36,public,test_table,pair,t)
 (1 row)

 Performing timescaledb-parallel-copy command...
  ttaCOPY 3748509
 Results:
  count
 -------
      0
 (1 row)
```

### How can we reproduce the bug?

Verify by unzipping the attached archive and running the "run" shell script. Out of caution, I included an obfuscated version of the crypto data in question. It has the same datatypes and the same dimensions as the original, unobfuscated csv. The script performs a vanilla postgres \COPY command on the csv and selects the row that I found to be missing when I discovered the bug (proving that COPY does, in fact, include the row). Then, the script clears all data out of the DB and repeats the copy, this time using timescaledb-parallel-copy. It then performs a selection to show the row in question is no longer there, despite supposedly being copied from an identical csv

**Comment by mkindahl** [comment]
@hjfeldy  Thanks for the bug report. Since this seems to be an issue with `timescaledb-parallel-copy` I move it over there.

**Comment by jchampio** [comment]
@hjfeldy Thanks for the report. It looks like the utility doesn't play well with the `HEADER` option you've specified -- Postgres will ignore the first line from every chunk, which is where your missing rows are going.

I suggest using `-skip-header` instead. If I switch your script from using
```
timescaledb-parallel-copy -file obf.csv -workers 1 -db-name $DB_NAME -connection "${CON_STRING}" -table test_table -copy-options "CSV HEADER"
```
to
```
timescaledb-parallel-copy -file obf.csv -workers 1 -db-name $DB_NAME -connection "${CON_STRING}" -table test_table -skip-header
```
then your test passes, and I can see the expected number of rows in the table. Does that work for you?

**Comment by danlmr** [comment]
I see this has been open a while, I've just run in to this same bug and it's created a bit of a mess as I am missing every 5kth row from the import data which is a bit of a challenge to unpick now I've continued importing other data as there was no warning of an issue at the time.

I appreciate it might be a tricky bug to resolve so would it be worth adding a warning or error if the header option is passed, or otherwise documenting this limitation or in the meantime?

**Comment by JamesGuthrie** [comment]
It seems to me as though providing the `HEADER` value to `-copy-options` is going to do something unexpected more often than not.

For this reason, I propose that we do the following: If we detect `HEADER` passed to `-copy-options`, we error out with a warning saying something like "you probably don't want to use `HEADER`, but if you really do, add the `-dangerous-force-header-copy-option` argument".

This would be a breaking change, but it seems to me that this is okay for the following reasons:
1. timescaledb-parallel-copy isn't 1.0 yet
2. it optimizes for the common case
3. failure in the uncommon case is simple to remedy

@danlmr @hjfeldy what do you think? Could you provide more context on why you thought that you needed to use `HEADER` in the first place?

**Comment by danlmr** [comment]
That sounds like a good idea to me @JamesGuthrie.

It wasn't really that I thought I needed the `HEADER` param, in my case the source that generated the export included a header and I'd previously imported this data into an on-prem installation using `COPY` so just used the same options. I guess there was no benefit from the header arg other than the header just happened to be present in the file and I hadn't foreseen the problems it would cause for the batching operation.

**Comment by JamesGuthrie** [comment]
@danlmr Aha, in that case, you should probably have used the `-skip-header` option to `timescaledb-parallel-copy`, instead of providing `HEADER` to `-copy-options`, and we should ensure that the warning output I mentioned above accounts for that.
