### ISSUE TITLE
Option 'truncate' truncates wrong table

### ISSUE THREAD

**Issue by fvannee** [timescale/timescaledb-parallel-copy#6]
The Truncate option does not take into account schema but just truncates the table named table_name in the public schema. This is not really desired behavior when copying data from a table in the public schema to a table with the same name in another schema. :-) Please prefix schema_name in the truncate command (line 75) to avoid people losing their data.

**Comment by RobAtticus** [comment]
Yikes, good catch! PR opened.

**Comment by RobAtticus** [comment]
Merged, thanks!
