### ISSUE TITLE
Installation fails on go1.9.2

### ISSUE THREAD

**Issue by loeken** [timescale/timescaledb-parallel-copy#8]
postgres@server:~$ go version
go version go1.9.2 linux/amd64
postgres@server:~$ go get github.com/timescale/timescaledb-parallel-copy
# runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:8:24: ArchFamily redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:8:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:8:24: undefined: WASM
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:9:24: BigEndian redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:9:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:10:24: CacheLineSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:10:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:11:24: DefaultPhysPageSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:11:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:12:24: PCQuantum redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:12:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:13:24: Int64Align redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:13:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:14:24: HugePageSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:14:29
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:15:24: MinFrameSize redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:15:24
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:18:6: Uintreg redeclared in this block
	previous declaration at /usr/local/go/src/runtime/internal/sys/arch_amd64.go:18:6
/usr/local/go/src/runtime/internal/sys/arch_wasm.go:8:24: too many errors

**Comment by RobAtticus** [comment]
Hmm, unable to reproduce on an instance of Ubuntu 16.04. Have you tried upgrading to the latest 1.9 version, or alternatively updating to go 1.11? Never seen an error like that and it doesn't seem to be anything related to our code...

**Comment by loeken** [comment]
Okey, to clarify i did test on debian 9 amd64. the errors I posted above occured with go1.9.2 linux/amd64. 

I then went on to test version 1.7 which was in the debian repos, which resulted in a slightly different error:

```
postgres@server:~$ go version
go version go1.7.4 linux/amd64
postgres@server:~$ go get github.com/timescale/timescaledb-parallel-copy
# github.com/jmoiron/sqlx
go/src/github.com/jmoiron/sqlx/sqlx.go:232: undefined: sql.ColumnType
go/src/github.com/jmoiron/sqlx/sqlx.go:234: undefined: sql.ColumnType
go/src/github.com/jmoiron/sqlx/sqlx.go:236: r.rows.ColumnTypes undefined (type *sql.Rows has no field or method ColumnTypes)
# github.com/lib/pq
go/src/github.com/lib/pq/notify.go:790: undefined: time.Until
```

good suggestions trying version 1.11 this one actually worked for me, thanks

**Comment by RobAtticus** [comment]
Hmm, I wonder if you fetched an old version of the dependencies or something? I'm glad it works for you though now.
