### ISSUE TITLE
pq: invalid input syntax for type double precision

### ISSUE THREAD

**Issue by k1ng440** [timescale/timescaledb-parallel-copy#9]

**Comment by RobAtticus** [comment]
Can you give me a few lines to work with? In a private message on slack is fine too, but I have no way to reproduce your problem with the info given.

**Comment by mathiasose** [comment]
I got this error because I had `NULL` values in my CSV that were represented by empty strings. I used `--copy-options="NULL ''"` to make it understand what they were.

**Comment by RobAtticus** [comment]
There seems to be a fine workaround, so I will close this unless it turns out to be a different issue. Thanks @mathiasose
